import { colProps } from "element-plus";
import { ref } from "vue"; // Import the ref function from the Vue Composition API

/* Thats the tableHeader for the table in index file */
export const tableHeader = [
  {
    columnName: "الرقم التسلسلي",
    columnLabel: "serial",
  },
  {
    columnName: "اسم المريض",
    columnLabel: "name",
  },
  {
    columnName: "العمر",
    columnLabel: "age",
  },
  {
    columnName: "الفئة",
    columnLabel: "degree",
  },
  {
    columnName: "العنوان",
    columnLabel: "address",
  },
  {
    columnName: "الهاتف",
    columnLabel: "phone",
  },

  /* It's gonna be static, so you can use it as a constant for all table so we can use the dropdown actions */
  {
    columnName: "العمليات",
    columnLabel: "actions",
  },
];

/* Thats the formFields Export to create dynamic inputs */

export const formFields = [
  {
    label: "اسم المريض",
    name: "name",
    order: 1,
    placeholder: "ادخل اسم المريض",
    attributeType: "string",
    display: {
      create: true,
      list: true,
      view: true,
      edit: true,
    },
    allowedExtensions: [],
    options: [],
    rules: "required",
  },
  {
    label: "العمر",
    name: "age",
    order: 2,
    placeholder: "ادخل العمر",
    attributeType: "int",
    display: {
      create: true,
      list: true,
      view: true,
      edit: true,
    },
    allowedExtensions: [],
    options: [],
    rules: "required",
  },
  {
    label: "تاريخ الميلاد",
    name: "birthday",
    order: 3,
    placeholder: "ادخل تاريخ الميلاد",
    attributeType: "date",
    display: {
      create: true,
      list: true,
      view: true,
      edit: true,
    },
    allowedExtensions: [],
    options: [],
    rules: "required",
  },
  {
    label: "الرقم القومي",
    name: "nationalId",
    order: 4,
    placeholder: "ادخل الرقم القومي",
    attributeType: "string",
    display: {
      create: true,
      list: true,
      view: true,
      edit: true,
    },
    allowedExtensions: [],
    options: [],
    rules: "required",
  },
  {
    label: "الفئة",
    name: "degree",
    order: 5,
    placeholder: "ادخل الفئة",
    attributeType: "enumeration",
    display: {
      create: true,
      list: true,
      view: true,
      edit: true,
    },
    allowedExtensions: [],
    options: ["اجنبي", "عسكري", "مدني"],
    rules: "required",
  },
  {
    label: "الرتية",
    name: "rank",
    order: 6,
    placeholder: "ادخل الرتبة",
    attributeType: "string",
    display: {
      create: true,
      list: true,
      view: true,
      edit: true,
    },
    allowedExtensions: [],
    options: [],
    rules: "",
  },
  {
    label: "اسم الاب",
    name: "fatherName",
    order: 7,
    placeholder: "ادخل اسم الاب",
    attributeType: "string",
    display: {
      create: true,
      list: true,
      view: true,
      edit: true,
    },
    allowedExtensions: [],
    options: [],
    rules: "required",
  },
  {
    label: "الرقم القومي للاب",
    name: "fatherId",
    order: 8,
    placeholder: "ادخل الرقم القومي للاب",
    attributeType: "string",
    display: {
      create: true,
      list: true,
      view: true,
      edit: true,
    },
    allowedExtensions: [],
    options: [],
    rules: "required",
  },
  {
    label: "اسم الام",
    name: "motherName",
    order: 9,
    placeholder: "ادخل اسم الام",
    attributeType: "string",
    display: {
      create: true,
      list: true,
      view: true,
      edit: true,
    },
    allowedExtensions: [],
    options: [],
    rules: "required",
  },
  {
    label: "الرقم القومي للام",
    name: "motherId",
    order: 10,
    placeholder: "ادخل الرقم القومي للام",
    attributeType: "string",
    display: {
      create: true,
      list: true,
      view: true,
      edit: true,
    },
    allowedExtensions: [],
    options: [],
    rules: "required",
  },
  {
    label: "العنوان",
    name: "address",
    order: 11,
    placeholder: "ادخل العنوان",
    attributeType: "string",
    display: {
      create: true,
      list: true,
      view: true,
      edit: true,
    },
    allowedExtensions: [],
    options: [],
    rules: "required",
  },
  {
    label: "الهاتف",
    name: "phone",
    order: 12,
    placeholder: "ادخل الهاتف",
    attributeType: "string",
    display: {
      create: true,
      list: true,
      view: true,
      edit: true,
    },
    allowedExtensions: [],
    options: [],
    rules: "required",
  },
  {
    label: "واتساب",
    name: "whatsapp",
    order: 13,
    placeholder: "ادخل رقنم الواتساب",
    attributeType: "string",
    display: {
      create: true,
      list: true,
      view: true,
      edit: true,
    },
    allowedExtensions: [],
    options: [],
    rules: "",
  },
];

/* Thats the formFields Export to create dynamic inputs */
export const formData = ref({
  name: "",
  age: 0,
  birthday: "",
  nationalId: "",
  degree: "",
  rank: "",
  fatherName: "",
  fatherId: "",
  motherName: "",
  motherId: "",
  address: "",
  phone: "",
  whatsapp: "",
});
